server:
  port: 8095
spring:
  application:
    name: authentication-service
  datasource:
    name: user
    url: jdbc:mysql://localhost:3306/user?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      import-check:
        enabled: false
management:
  security:
    enabled: false
  application:
    name: authentication-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



# spring:
#   application:
#     name: authentication-service
#   cloud:
#     config:
#       uri: http://localhost:8888/
# management:
#   security:
#     enabled: false

# eureka:
#   client:
#     registerWithEureka: true
#     fetchRegistry: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost
