eureka: 
  client: 
    fetch-registry: true
    register-with-eureka: true
  service-url: 
    defaultZone: "http://localhost8761/eureka"
server: 
  port: 8081
spring:
  application:
    name: user-service
  data: 
    mongodb: 
      database: players
      host: localhost
      port: 27017
  datasource: 
    driver-name: mongodb.jdbc.MongoDriver

# spring:
#   application:
#     name: user-service
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check:
#         enabled: false
# management:
#   security:
#     enabled: false
