server:
  port: 8087
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Bookings
  application:
    name: bookings-management


# server:
#   port: 8087
# spring:
#   data:
#     mongodb:
#       host: localhost
#       port: 27017
#       database: Bookings
#   application:
#     name: bookings-management
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check.enabled: false
# management:
#   security:
#     enabled: false
